apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: ${WORKLOAD_NAME}
  annotations:
    alpha.jobset.sigs.k8s.io/exclusive-topology: cloud.google.com/gke-nodepool
spec:
  ttlSecondsAfterFinished: 3600
  failurePolicy:
    maxRestarts: 0
    rules:
      - action: FailJobSet
        onJobFailureReasons:
          - PodFailurePolicy
  replicatedJobs:
    - name: main-job
      replicas: 1
      template:
        spec:
          parallelism: 32
          completions: 32
          backoffLimit: 0
          template:
            metadata:
              annotations:
                cloud.google.com/gke-tpu-slice-topology: 4x4x8
            spec:
              hostNetwork: true
              dnsPolicy: ClusterFirstWithHostNet
              terminationGracePeriodSeconds: 30
              restartPolicy: Never
              containers:
              - name: workload-container
                image: ${WORKLOAD_IMAGE}
                command:
                - "/bin/bash"
                - "-c"
                - "set -e && set -o pipefail && export ENABLE_PATHWAYS_PERSISTENCE='1' && export LIBTPU_INIT_ARGS='   --xla_tpu_scoped_vmem_limit_kib=65536   --xla_tpu_bf16_emission_mode=NATIVE_EMISSION   --xla_tpu_enable_sparse_core_reduce_scatter_v2=true   --xla_tpu_enable_sparse_core_collective_offload_all_gather=true   --xla_tpu_enable_sparse_core_collective_offload_2d_all_gather=true   --xla_tpu_enable_all_gather_offload_tracing=true   --xla_tpu_use_tc_device_shape_on_sc=True   --xla_sc_disable_megacore_partitioning=True   --xla_tpu_enable_async_collective_fusion_fuse_all_gather=false   --xla_enable_async_all_gather=true   --xla_tpu_prefer_async_allgather_to_allreduce=true   --xla_tpu_enable_sparse_core_collective_offload_all_reduce=true   --xla_tpu_enable_sparse_core_collective_offload_reduce_scatter=true   --xla_tpu_enable_sparse_core_collective_offload_3d_all_gather=true   --xla_tpu_use_single_sparse_core_for_all_gather_offload=true   --xla_tpu_enable_concurrent_sparse_core_offloading=true   --xla_tpu_aggressive_opt_barrier_removal=true   --xla_tpu_enable_offloading_gather_to_sparsecore=true   --xla_tpu_sparse_core_all_gather_latency_multiplier=1   --xla_tpu_sparse_core_reduce_scatter_latency_multiplier=3   --xla_tpu_enable_sparse_core_collective_aggregator=true   --xla_tpu_enable_latency_hiding_layer_scheduler=true   --xla_tpu_scheduler_percent_shared_memory_limit=150   --xla_tpu_enable_layer_scheduler_for_dependent_collectives=true   --xla_tpu_enable_sparse_core_collective_offload_nd_reduce_scatter=true   --xla_tpu_pcie_bandwidth_multiplier=0.03   --xla_tpu_enable_sparse_core_offload_queuing_in_lhs=true   --xla_tpu_enable_multi_compute_overlap_in_layer_scheduler=false   --xla_tpu_enable_3d_reduce_scatter_decomposer=false ' && export ARTIFACT_DIR='${BASE_OUTPUT_DIR}/${WORKLOAD_NAME}' && export JAX_PLATFORMS='tpu,cpu' && export ENABLE_PJRT_COMPATIBILITY='true' && set +e; python3 -u -m maxtext.trainers.pre_train.train maxtext/configs/base.yml model_name=deepseek3-671b per_device_batch_size=8.0 max_target_length=4096 dcn_pipeline_parallelism=1 dcn_data_parallelism=-1 ici_pipeline_parallelism=1 ici_fsdp_transpose_parallelism=1 ici_fsdp_parallelism=-1 allow_split_physical_axes=True use_iota_embed=True remat_policy=custom decoder_layer_input=offload opt_type=adamw mu_dtype=bfloat16 grad_dtype=bfloat16 use_random_routing=True megablox=True sparse_matmul=True use_custom_sort_vjp=True shard_exp_on_fsdp=True sa_use_fused_bwd_kernel=True sa_block_q=2048 sa_block_kv=2048 sa_block_q_dkv=2048 sa_block_kv_dkv=2048 sa_block_kv_dkv_compute=2048 sa_block_kv_dq=2048 sa_block_q_dq=2048 attention=flash use_tokamax_splash=True use_max_logit_estimate=-1 cost_estimate_flops_fwd=5000000000000 cost_estimate_flops_bwd=5000000000000 float32_weight_sum=False use_tokamax_gmm=True tokenizer_path=assets/tokenizer.mistral-v3 dataset_type=synthetic dataset_path=gs://max-datasets-rogue enable_checkpointing=False steps=30 base_output_directory=${BASE_OUTPUT_DIR} run_name=${WORKLOAD_NAME} | tee train.log; TRAIN_EXIT_CODE=${PIPESTATUS[0]}; if [ -s train.log ]; then timeout 30s gcloud storage cp --no-user-output-enabled train.log ${ARTIFACT_DIR}/logs/train-${TPU_WORKER_ID:-${JOB_COMPLETION_INDEX:-${HOSTNAME:-0}}}.log || true; fi; exit ${TRAIN_EXIT_CODE}"
                resources:
                  limits:
                    google.com/tpu: "4"
                env:
                - name: TPU_STDERR_LOG_LEVEL
                  value: "0"
                - name: TPU_MIN_LOG_LEVEL
                  value: "0"
                - name: TF_CPP_MIN_LOG_LEVEL
                  value: "0"
                - name: TPU_VMODULE
                  value: "real_program_continuator=1"
              nodeSelector:
                cloud.google.com/gke-tpu-accelerator: tpu7x
                cloud.google.com/gke-tpu-topology: 4x4x8
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: cloud.google.com/gke-nodepool
                        operator: NotIn
                        values:
                        - default-pool
              tolerations:
                - effect: NoSchedule
                  key: google.com/tpu
                  operator: Exists