apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hyperdisk-balanced-tpu
provisioner: pd.csi.storage.gke.io
parameters:
  type: hyperdisk-balanced
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hd-claim
spec:
  storageClassName: hyperdisk-balanced-tpu
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-tpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-tpu
  template:
    metadata:
      labels:
        app: vllm-tpu
    spec:
      nodeSelector:
        cloud.google.com/gke-tpu-accelerator: tpu7x
        cloud.google.com/gke-tpu-topology: 1x1x1
      containers:
      - name: vllm-tpu
        image: vllm/vllm-tpu:nightly-20260914-2ea06d0-51da0ca
        command: ["python3", "-m", "vllm.entrypoints.openai.api_server"]
        args:
        - --host=0.0.0.0
        - --port=8000
        - --seed=42
        - --model=Qwen/Qwen3-32B
        - --tensor-parallel-size=2
        - --data-parallel-size=1
        - --max-model-len=9216
        - --max-num-batched-tokens=4096
        - --max-num-seqs=320
        - --gpu-memory-utilization=0.98
        - --block-size=256
        - --kv-cache-dtype=fp8
        - --no-enable-prefix-caching
        - --async-scheduling
        - '--additional-config={"quantization": {"qwix": {"rules": [{"module_path": ".*", "weight_qtype": "float8_e4m3fn", "act_qtype": "float8_e4m3fn"}]}}, "compilation_sizes": [96, 160, 192, 224, 288, 320]}'
        - --download-dir=/data
        env:
        - name: HF_HOME
          value: /data
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: hf_api_token
        - name: LAYOUT_Q_PROJ_AS_NDH
          value: "1"
        - name: USE_BATCHED_RPA_KERNEL
          value: "1"
        ports:
        - containerPort: 8000
        resources:
          limits:
            google.com/tpu: '1'
          requests:
            google.com/tpu: '1'
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        volumeMounts:
        - mountPath: "/data"
          name: data-volume
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
      - name: data-volume
        persistentVolumeClaim:
          claimName: hd-claim
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-service
spec:
  selector:
    app: vllm-tpu
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
